### ISSUE TITLE
Fix NoClassDefFoundError when attempting to run application.

### ISSUE THREAD

**Issue by james-cathcart** [james-cathcart/r2dbc-example#2]
When attempting to run the application, it fails on a NoClassDefFoundError for unknown reasons.

Stacktrace:
```
2019-07-25 20:20:18.666  INFO 1154 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-25 20:20:18.671 ERROR 1154 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: org/springframework/transaction/reactive/TransactionSynchronizationManager
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.doGetConnection(ConnectionFactoryUtils.java:88) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.getConnection(ConnectionFactoryUtils.java:70) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.getConnection(DefaultDatabaseClient.java:189) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnectionMany(DefaultDatabaseClient.java:170) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultFetchSpec.all(DefaultFetchSpec.java:75) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultFetchSpec.first(DefaultFetchSpec.java:67) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultSqlResult.first(DefaultSqlResult.java:132) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedInsertSpec$1.lambda$first$1(DefaultDatabaseClient.java:1020) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:141) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.MonoDefaultIfEmpty.subscribe(MonoDefaultIfEmpty.java:37) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3954) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3842) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3809) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3756) ~[reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at com.madhax.reactivesql.bootstrap.Bootstrap.initData(Bootstrap.java:34) ~[classes/:na]
	at com.madhax.reactivesql.bootstrap.Bootstrap.run(Bootstrap.java:26) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.madhax.reactivesql.ReactivesqlApplication.main(ReactivesqlApplication.java:12) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.transaction.reactive.TransactionSynchronizationManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 24 common frames omitted


Process finished with exit code 1
```

**Comment by james-cathcart** [comment]
Fixed, need to include the spring-boot-starter dependency. 7cc4118df03c431b4903236163052401ca134bf2
